# Generated by Django 3.0.3 on 2020-06-10 03:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Edad', models.SmallIntegerField(default=0, verbose_name='Edad')),
                ('Profesion', models.CharField(max_length=100, verbose_name='Profesion0')),
                ('Perfil', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('Creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('Actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['Creado'],
            },
        ),
    ]
